# Generated by Django 3.1.2 on 2020-10-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=6)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('help_me', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'strawberry',
            },
        ),
    ]
